### PR TITLE
update BraTS-Toolkit tutorial 

### PR DESCRIPTION
**Pull request by evamariie**
- notebook: added picture, some cells with Markdown/description and path descriptions 
- changed path name for easy usage in notebook and colab 
- updated/added visualizations in 
 a) notebook (tumor visible in example slices + sequence as title)
 b) utils (function: visualize_data2)
- runs in linus (no errors)

### CODE REVIEW

**Comment by neuronflow** [comment]
@MarcelRosier our formatting fails, there's a node error msg. Can you have a look please?

**Comment by MarcelRosier** [comment]
fixed node version, but that wasnt the issue.
I think the format action fails because the PR isnt from a branch but from a fork and the action does not have permission to checkout the fork afterbeing triggered by a comment. not sure if this can be easily resolved. in the meantime either fix the formatting issue locally:
```sh
$ pip install black
$ black .
```
or use a regular branch instead of a fork @neuronflow @evamariie

**Comment by neuronflow** [comment]
Thanks for looking into it @MarcelRosier !

@evamariie please install black and format your code (do this for all PRs). You will probably need the Jupyter version of black. I will add you as a developer for this repo, so you don't need to fork in the future and can enjoy the brainless bot :)

**Comment by MarcelRosier** [comment]
ok the lint action will also not work properly for forks since it depends on env secrets that can not be accessed in PRs from a fork.

**Review by neuronflow — APPROVED** [review]

**Pull request merged**
